---
# repo: jomrr/ansible-molecule-images
# file: .pre-commit-config.yaml

repos:
  - repo: local
    hooks:
      - id: commitizen
        name: commitizen
        entry: .venv/bin/cz check --commit-msg-file
        language: system
        stages: [commit-msg]
