---
# name: ansible-molecule-images
# file: containers.yml

all:
  vars:
    ansible_connection: local
    build_maintainer: "Jonas Mauer <jam@kabelmail.net>"
    container_registry: docker.io
    push_registries:
      - name: docker.io
        username: "{{ lookup('ansible.builtin.env', 'DOCKER_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'DOCKER_SECRET') }}"
  children:
    almalinux:
      hosts:
        almalinux-9:
          build_tags:
            - 9
            - latest
        almalinux-8:
          build_tags:
            - 8
      vars:
        build_image: almalinux
        container_image: almalinux
    alpine:
      hosts:
        alpine-3.20:
          build_tags:
            - "3.20"
            - 3
            - latest
        alpine-3.19:
          build_tags:
            - 3.19
        alpine-3.18:
          build_tags:
            - 3.18
      vars:
        build_image: alpine
        container_image: alpine
    amazonlinux:
      hosts:
        amazonlinux-2023:
          build_tags:
            - 2023
            - latest
      vars:
        build_image: amazonlinux
        container_image: amazonlinux
    archlinux:
      hosts:
        archlinux-latest:
          build_tags:
            - latest
      vars:
        build_image: archlinux
        container_image: archlinux
    debian:
      hosts:
        debian-13:
          build_tags:
            - trixie
            - 13
        debian-12:
          build_tags:
            - bookworm
            - 12
            - latest
            - stable
        debian-11:
          build_tags:
            - bullseye
            - 11
            - oldstable
        debian-10:
          build_tags:
            - buster
            - 10
            - oldoldstable
        debian-sid:
          build_tags:
            - sid
            - unstable
        debian-testing:
          build_tags:
            - testing
      vars:
        build_image: debian
        container_image: debian
    fedora:
      hosts:
        fedora-42:
          build-tags:
            - 42
            - latest
        fedora-41:
          build_tags:
            - 41
        fedora-rawhide:
          build_tags:
            - 43
            - rawhide
      vars:
        build_image: fedora
        container_image: fedora
    opensuse:
      hosts:
        opensuse-leap-15.6:
          build_tags:
            - 15.6
            - 15
            - latest
        opensuse-tumbleweed:
          build_image: opensuse-tumbleweed
          build_tags:
            - latest
          container_image: opensuse/tumbleweed
      vars:
        build_image: opensuse-leap
        container_image: opensuse/leap
    oraclelinux:
      hosts:
        oraclelinux-9:
          build_tags:
            - 9
            - latest
        oraclelinux-8:
          build_tags:
            - 8
      vars:
        build_image: oraclelinux
        container_image: oraclelinux
    ubuntu:
      hosts:
        ubuntu-24.04:
          build_tags:
            - 24.04
            - noble
            - latest
        ubuntu-22.04:
          build_tags:
            - 22.04
            - jammy
        ubuntu-20.04:
          build_tags:
            - 20.04
            - focal
      vars:
        build_image: ubuntu
        container_image: ubuntu
