---
# name: ansible-molecule-images
# file: playbooks/vars/almalinux.yml

dockerfile:
  from: "{{ pull_registry }}/{{ pull_image }}"
  entrypoint: "/usr/lib/systemd/systemd"
  environment:
    container: docker
  package_update: "yum -qy update --refresh && yum -y install rpm centos-release dnf-plugins-core"
  package_install: "yum -qy --nodocs --setopt=tsflags=nodocs install"
  packages:
    - bash
    - findutils
    - hostname
    - initscripts
    - iproute
    - passwd
    - procps-ng
    - python3
    - sudo
    - systemd-libs
  package_clean: "yum -qy autoremove && yum -qy clean all"
  commands:
    - find /etc/systemd/system /lib/systemd/system -path 'sysinit.target.wants/*' -not -name '*systemd-tmpfiles*' -delete
    - rm -f /lib/systemd/system/multi-user.target.wants/*
    - rm -f /etc/systemd/system/*.wants/*
    - rm -f /lib/systemd/system/local-fs.target.wants/*
    - rm -f /lib/systemd/system/sockets.target.wants/*udev*
    - rm -f /lib/systemd/system/sockets.target.wants/*initctl*
    - rm -f /lib/systemd/system/basic.target.wants/*
    - rm -f /lib/systemd/system/anaconda.target.wants/*
    - systemctl enable dbus.socket
    - systemctl enable dbus-broker.service
    - systemctl mask getty.service
    - >-
      printf "%s\n"
      "auth sufficient pam_rootok.so"
      "account sufficient pam_permit.so"
      "session optional pam_keyinit.so revoke"
      "session required pam_limits.so"
      > /etc/pam.d/sudo
    - 'test ! -f /etc/pam.d/sudo-i || cp -a /etc/pam.d/sudo /etc/pam.d/sudo-i'
    - 'getent group 1000 >/dev/null || groupadd -g 1000 ansible'
    - 'getent passwd 1000 >/dev/null || useradd -u 1000 -g 1000 -m -s /bin/bash ansible'
    - 'passwd -l ansible || true'
    - 'getent group 1001 >/dev/null || groupadd -g 1001 molecule'
    - 'getent passwd 1001 >/dev/null || useradd -u 1001 -g 1001 -m -s /bin/bash molecule'
    - 'passwd -l molecule || true'
    - 'touch /etc/sudoers'
    - 'sed -i -E "/^[[:space:]]*root[[:space:]]+/d" /etc/sudoers'
    - 'sed -i -E "s/^([[:space:]]*Defaults[[:space:]]+requiretty)/#\1/" /etc/sudoers'
    - 'printf "\n%s\n" "root ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers'
    - 'printf "%s\n" "ALL ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers'
    - 'chown root:root /etc/sudoers'
    - 'chmod 0440 /etc/sudoers'
    - 'visudo -cf /etc/sudoers'
