---
# name: ansible-molecule-images
# file: playbooks/vars/archlinux.yml

dockerfile:
  from: "{{ container_registry }}/{{ container_image }}"
  entrypoint: "/usr/lib/systemd/systemd"
  environment:
    container: docker
  package_update: "pacman -Syu --noconfirm"
  package_install: "pacman -Sy --noconfirm"
  packages:
    - bash
    - systemd-sysvcompat
    - procps-ng
    - python3
    - sudo
  # "pacman -Scc --noconfirm" =~ apt clean (clean all cache)
  # "pacman -Sc --noconfirm" =~ apt autoclean (clean out of date cache)
  # "pacman -Rns $(pacman -Qtdq) --noconfirm" =~ apt autoremove (remove unused packages)
  package_clean: "pacman -Rns $(pacman -Qtdq) --noconfirm"
  commands:
    - find /etc/systemd/system /lib/systemd/system -path 'sysinit.target.wants/*' -not -name '*systemd-tmpfiles*' -delete
    - rm -f /lib/systemd/system/multi-user.target.wants/*
    - rm -f /etc/systemd/system/*.wants/*
    - rm -f /lib/systemd/system/local-fs.target.wants/*
    - rm -f /lib/systemd/system/sockets.target.wants/*udev*
    - rm -f /lib/systemd/system/sockets.target.wants/*initctl*
    - rm -f /lib/systemd/system/basic.target.wants/*
    - "systemctl mask getty.service"
    - "sed -i -e 's/^\\(Defaults\\s*requiretty\\)/#--- \\1/' /etc/sudoers"
