# repo: jomrr/ansible-molecule-images
# file: playbooks/templates/Dockerfile.j2

FROM {{ dockerfile.from }}:{{ push_tags[0] }}

# Set maintainer
LABEL maintainer="{{ build_maintainer }}"
LABEL org.opencontainers.image.authors="{{ build_maintainer }}"

# Set environment variables
{% for env_var, value in dockerfile.environment.items() %}
ENV {{ env_var }}={{ value }}
{% endfor %}

# Install dependencies and run commands
RUN {{ dockerfile.package_update }} && \
    {{ dockerfile.package_install }} {{ dockerfile.packages | join(' ') }} && \
    {{ dockerfile.package_clean }}; \
{% for command in dockerfile.commands %}
{% if loop.last %}
    {{ command }}
{% else %}
    {{ command }}; \
{% endif %}
{% endfor %}

# Set entrypoint
ENTRYPOINT ["{{ dockerfile.entrypoint }}"]
