---
# repo: jomrr/ansible-molecule-images
# file: playbooks/build.yml

- name: "PLAYBOOK | Generate Dockerfiles and build container images"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Import variable files"
      ansible.builtin.include_vars:
        file: "{{ lookup('ansible.builtin.first_found', params) }}"
      vars:
        params:
          files:
            - "{{ inventory_hostname }}.yml"
            - "{{ push_image }}.yml"
          paths:
            - 'vars'
          skip: false

    - name: "Create build directory"
      ansible.builtin.file:
        path: "{{ build_dir }}/{{ push_image }}"
        state: directory
        mode: '0755'

    - name: "Generate Dockerfile"
      ansible.builtin.template:
        src: "templates/Dockerfile.j2"
        dest: "{{ build_dir }}/{{ push_image }}/{{ inventory_hostname }}"
        mode: '0644'

    - name: "Generate tag/push matrix"
      no_log: "{{ build_no_log }}"
      ansible.builtin.set_fact:
        _targets: "{{ (_targets | default([])) + [target_spec] }}"
      vars:
        registry: "{{ pair.0 }}"
        push_tag: "{{ pair.1 }}"
        target_spec:
          registry: "{{ registry.name }}"
          username: "{{ registry.username }}"
          password: "{{ registry.password }}"
          repo: "{{ push_repo }}"
          image: "{{ push_image }}"
          tag: "{{ push_tag }}"
          path: "{{ build_dir }}/{{ push_image }}"
          file: "{{ build_dir }}/{{ push_image }}/{{ inventory_hostname }}"
          origin: "{{ registry.name }}/{{ registry.username }}/{{ push_repo }}"
          target: "{{ registry.name }}/{{ registry.username }}/{{ push_repo }}:{{ push_tag }}"
      loop: "{{ push_registries | product(push_tags) | list }}"
      loop_control:
        loop_var: pair
        label: "{{ pair.0.name }}/{{ pair.0.username }}/{{ push_repo }}:{{ pair.1 }}"

    - name: "Build container images and push to registries"
      no_log: "{{ build_no_log }}"
      containers.podman.podman_image:
        name: "{{ item.origin }}"
        build:
          file: "{{ item.file }}"
          force_rm: true
          format: docker
        force: true
        path: "{{ item.path }}"
        state: build
        tag: "{{ item.tag }}"
        push: true
        username: "{{ item.username }}"
        password: "{{ item.password }}"
      loop: "{{ _targets }}"
      loop_control:
        loop_var: item
        label: "{{ item.target }}"
